Feature/exporter
stackmon/status-dashboard pull request #65
Opened 2023-09-08 14:10 UTC by bakhterets

It may need to add some more tests or changes

2023-09-12 07:01 UTC, anton-sidelnikov requested changes

2023-09-12 07:01 UTC, anton-sidelnikov commented on app/exporter/routes.py
> +        db.session.execute(text("SELECT 1")).scalar()
method connect do not fit here?

2023-09-15 18:04 UTC, gtema requested changes

2023-09-21 10:36 UTC, anton-sidelnikov approved these changes

2024-06-05 09:35 UTC, closed without merging